language: python
python:
- '3.4'
addons:
  apt:
    packages:
    - python3-lxml
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_872cfdcad6a5_key -iv $encrypted_872cfdcad6a5_iv
  -in travis/secrets.tar.gz.enc -out travis/secrets.tar.gz -d
- tar xvf travis/secrets.tar.gz -C travis
install:
- pip install -r ./travis/requirements.txt
script:
- python ./travis/test_json.py
- py.test . -v --cov . --cov-report term-missing
after_success:
- coveralls
- travis/deploy.sh
env:
- PYTHONPATH=.
notifications:
  irc:
    channels:
    - chat.freenode.net#yacah
    template:
    - '%{repository_name}#%{build_number} (%{branch} - %{commit}) %{author}: "%{commit_message}"
      %{message}'
    skip_join: true
  email: false
