language: python
python:
  - "3.4"

install:
  - "sudo apt-get update -q"
  - "sudo apt-get install -y python3-lxml"
  - "pip install -r ./travis/requirements.txt"

script:
  - "python ./travis/test_json.py"
  - "py.test . -v --cov . --cov-report term-missing"

after_success:
  - "coveralls"

env:
  - PYTHONPATH=.

notifications:
  irc:
    channels:
      - "chat.freenode.net#yacah"
    template:
      - "%{repository_name}#%{build_number} (%{branch} - %{commit}) %{author}: %{commit_message} %{message} %{result}"
  on_failure: always
  on_success: change
